package eventgamescollection.exceptions.groupsExceptions;

import eventgamescollection.exceptions.RuntimeEventGamesCollectionException;

public class GroupException extends RuntimeEventGamesCollectionException {
}
